server:
  port: 8761

spring:
  application:
    name: euremka-server

# eureka server 配置
eureka:
  client:
    #是否将自己注册到注册中心
    registerWithEureka: false
    #是否从EurekaServer 获取注册信息
    fetchRegistry: false
    #设置与eureka交互的地址
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
