spring:
  application:
    name: user-consumer
eureka:
  client:
    service-url:
      defaultZone: http://43.155.134.153:8761/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8763
ribbon:
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
feign:
  hystrix:
    enabled: true